version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: onkar
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: StudentAppUsingDocker
    ports:
      - 5433:5432
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
